cluster_name: "default-cluster"
show_hostname: false
check_interval: "30s"
# minutes
alert_silence_duration: 5
telegram:
  bot_token: ""
  chat_id: ""
monitoring:
  enabled: false
rabbitmq:
  enabled: false
  url: "http://localhost:15672"
  address: "http://localhost:15672" # Added for management API
  username: "guest"
  password: "guest"
  cluster_name: "rabbitmq-cluster"
redis:
  enabled: false
  addr: "localhost:6379"
  password: ""
  db: 0
  cluster_name: "redis-cluster"
  big_key_threshold: 1048576
mysql:
  enabled: false
  dsn: "root:password@tcp(localhost:3306)/mysql"
  cluster_name: "mysql-cluster"
  max_connections: 100
nacos:
  enabled: false
  address: "http://localhost:8848"
  cluster_name: "nacos-cluster"
host_monitoring:
  enabled: false
  cpu_threshold: 80.0
  mem_threshold: 80.0
  disk_threshold: 90.0
  net_io_threshold: 1.0
  disk_io_threshold: 1.0
system_monitoring:
  enabled: false