cluster_name: "default-cluster"
show_hostname: false
check_interval: "30s"
#
monitor_web_url: "http://192.168.3.92:8080/api/alerts"
retry_times: 3
retry_delay: "5s"
# minutes
alert_silence_duration: 5
telegram:
  bot_token: ""
  chat_id: ""
monitoring:
  enabled: false
rabbitmq:
  enabled: false
  url: "http://localhost:15672"
  address: "http://localhost:15672" # Added for management API
  username: "guest"
  password: "guest"
  cluster_name: "rabbitmq-cluster"
redis:
  enabled: false
  addr: "localhost:6379"
  password: ""
  db: 0
  cluster_name: "redis-cluster"
  big_key_threshold: 1048576
mysql:
  enabled: false
  dsn: "root:password@tcp(localhost:3306)/mysql"
  cluster_name: "mysql-cluster"
  deadlock_threshold: 10
  slow_query_threshold: 30
  max_connections: 100
  seconds_behind_threshold: 5
nacos:
  enabled: false
  address: "http://localhost:8848"
  cluster_name: "nacos-cluster"
  nacos_data_id: "example"
  nacos_group: "DEFAULT_GROUP"
host_monitoring:
  enabled: false
  cpu_threshold: 80.0
  mem_threshold: 80.0
  disk_threshold: 90.0
  net_io_threshold: 1.0
  disk_io_threshold: 1.0
system_monitoring:
  enabled: false